export const FETCH_POSTs = 'FETCH_POSTs'
export const UPDATE_POSTS = 'UPDATE_POSTS'

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS'
export const UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS'