export const FETCH_POSTs = 'FETCH_POSTs'
export const UPDATE_POSTS = 'UPDATE_POSTS'
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR'

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS'
export const UPDATE_POST_COMMENTS = 'UPDATE_POST_COMMENTS'
export const FETCH_POST_COMMENT_ERROR = 'FETCH_POST_COMMENT_ERROR'